version: '3.7'
services: 

 frontend:
    build: './frontend-example-docker'
    image: nodefront
    ports:
      - "5000:5000"
    depends_on:
      - backend

 backend:
    build: './backend-example-docker'
    image: nodeback
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379
      - REDIS=redis



 redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"    
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis

